In [1]:
# numpy module in python 
import numpy as np 

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b = np.array([[0,9,8,9],[2,3,4,5]])
b

array([[0, 9, 8, 9],
       [2, 3, 4, 5]])

In [5]:
a.ndim # get the dimension 
b.shape  # get the shape

(2, 4)

In [6]:
a.dtype  # get the data type like here int32

dtype('int32')

In [8]:
a.view 

<function ndarray.view>

In [10]:
# press tab to see the various mehtods associated
a.itemsize  # size of array
len(a)     # same as above length of the array


4

In [13]:
a.nbytes  # total no of bytes used by array a
b.nbytes  # tala no of bytes(memory used by b)

32

In [17]:
# indexing and slicing 
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,14,45]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 14 45]]


In [15]:
#get a specific elemetn 
a[0,3]  # 0th row 4th element (0 based indexing)
# [startIndex:endIndex:stepSize]


4

In [18]:
a[0::, 1:]  # [startIndex:endIndex:stepsize, startIndex:endIndex:stepsize]abb

array([[ 2,  3,  4,  5,  6,  7],
       [ 9, 10, 11, 12, 14, 45]])

In [23]:
b = np.array([[1,2,3,4],[3,4,5,6],[6,7,8,5],[4,3,6,7]])
print(b)

[[1 2 3 4]
 [3 4 5 6]
 [6 7 8 5]
 [4 3 6 7]]


In [25]:
#get the sumatrix from 2nd row till 3row and 2nd column to last column 
print(b[1:3:,1::])

[[4 5 6]
 [7 8 5]]


In [27]:
#get a specific element 
b[2][2]  # first way
b[2,2]   # second way    both indexing in correct

8

In [33]:
# get a specific row
b[1,:] # all the element of the first row
b[1,::] 
b[1,]  # all the above three way is same for getting the a specific row

array([3, 4, 5, 6])

In [35]:
# getting a specific column 
b[:,2]  # all the element of the 2nd(3rd 0 based) column 

array([3, 5, 8, 6])

In [36]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 14, 45]])

In [38]:
# a little moere fancy 
a[0,1:-1:2]  # in first row till second last take step of 2

array([2, 4, 6])

In [40]:
# replacing the values 
# we can replace column sumbmatrix or anyting we like 
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 14, 45]])

In [44]:
a[0,2::] = 5 # replace all the values in 0th row from 2nd column to end with 5
print(a)

[[ 1  2  5  5  5  5  5]
 [ 8  9 10 11 12 14 45]]


In [45]:
# change a particular element 
a[1,2] = 4 # 2nd row third element changes to 4
a

array([[ 1,  2,  5,  5,  5,  5,  5],
       [ 8,  9,  4, 11, 12, 14, 45]])

In [46]:
# initilizing all the values with all zeros
a = np.zeros((5))
print(a)

[0. 0. 0. 0. 0.]


In [47]:
np.zeros((2,4)) # 2d array with all zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones((4,4),dtype = "int32")  # all the values initilized with all ones 
                                # we can pass the size of bytes what we want ot use like here int32 is enought to store the data
              

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
a = np.array(map(int,input().split())) # take all the values in form of array
a

5 6 7 8 4 2 1 3 4


array(<map object at 0x0000017618332610>, dtype=object)

In [54]:
# taking input like list comprehension 
np.array([x for x in input().split()],dtype = "int32") 


5 4 6 3 2 2 5 22


array([ 5,  4,  6,  3,  2,  2,  5, 22])

In [55]:
#initilizing with other numbers
np.full((2,4),6)  # first parameter is dimension 2ne one is vlaues 
# we can use othe mehtod "full_like" same as above


array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [60]:
# initilizing with random number
np.random.rand(5,4) # five rows and 4 column 2d array with values between 0 and 1

array([[0.49112365, 0.44026503, 0.54636183, 0.65594487],
       [0.36801284, 0.27336829, 0.74798603, 0.19300974],
       [0.04900025, 0.0259819 , 0.73596189, 0.43238108],
       [0.66553452, 0.02265763, 0.99648941, 0.77656282],
       [0.99397999, 0.90555994, 0.67243022, 0.05139329]])

In [61]:
np.random.randint(5,12)  # it will return a single random inteer between given parameter

8

In [67]:
np.random.randint(-1,6, size = (3,4)) # a (3,3) matrix with random values between -1 and 6

array([[ 3, -1,  1,  2],
       [ 0,  1,  2,  4],
       [ 4,  2,  2,  5]])

In [70]:
# indentity matrix 
np.identity(5) # a 5 by 5 identity matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
arr = np.array([[1,2,3,4]])
r = np.repeat(arr,3,axis = 0)   # repeate the array 3 times (axis 0 for rows) 
print(r)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [75]:
r = np.repeat(arr,2,axis = 1) # it keep the elemtn in sorted order
print(r) 

[[1 1 2 2 3 3 4 4]]


In [84]:
# make 2d arrary all the boundary elements are 1 and all the and middle element is 5 and all the other elements are 0
x = np.ones((5,5))
print(x)
z = np.zeros((3,3))
print(z)
x[1:-1:,1:-1] = z # or x[1:4:,1:4:] or x[1]
print(x)

x[2][2] = 5
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 5. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [88]:
a = np.array([1,2,3])
b = a
#b[0] = 100
print(a)  # here by changing the values in b is also change because of reference
b = a.copy() # we can use copy function to make another copy insted referring previous one
print(b)


[1 2 3]
[1 2 3]


In [99]:
# mathmetics 
a = np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [106]:
a + 2  # add 2 to all the values

array([4, 5, 6, 7])

In [107]:
a - 2 # subtract -2 to all the values

array([0, 1, 2, 3])

In [108]:
a*3

array([ 6,  9, 12, 15])

In [109]:
a / 2

array([1. , 1.5, 2. , 2.5])

In [110]:
a 

array([2, 3, 4, 5])

In [111]:
b = np.array([2,5,6,3])
b

array([2, 5, 6, 3])

In [112]:
 a + b # vector addition (array addition )

array([ 4,  8, 10,  8])

In [118]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]]) # (3,3)
b = np.array([[1,2,1],[2,3,1],[3,4,1]]) # (3,3)

a * b  # simple multiplication (not matrix multiplication)

array([[1, 4, 3],
       [2, 6, 3],
       [3, 8, 3]])

In [119]:
np.sin(a)  # sin values of all the values of matrix

array([[0.84147098, 0.90929743, 0.14112001],
       [0.84147098, 0.90929743, 0.14112001],
       [0.84147098, 0.90929743, 0.14112001]])

In [ ]:

# Linear alebra (mathmetics)

In [121]:
a = np.full((2,3),1)
print(a)
b  = np.full((3,2),2)
print(b)

#matrix multiplicaiton of both matrix 
np.matmul(a,b) # 

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [124]:
np.linalg.det(np.identity(5))  #determinant of identity matrix

1.0

In [ ]:
# we can do all the stuf of the linear algebra revise those and come back again for doing

In [ ]:
# Statistics (mathmetics)

In [125]:
stats = np.array([[2,3,4],[4,5,6]])
print(stats)

[[2 3 4]
 [4 5 6]]


In [131]:
print(np.mean(stats)) # mean valus 24/6 = 4.
print(np.min(stats)) # min value 2
print(np.max(stats)) # max values

4.0
2
6


In [132]:
np.sum(stats)

24

In [135]:
np.min(stats,axis = 1) # min values of both column 
np.min(stats,axis = 0) # min values of rows

array([2, 3, 4])

In [ ]:
# Reoganizing Arrays

In [138]:
before = np.array([[1,2,3],[6,7,8]])
print(before) 

after = before.reshape(2,3) # make sure the values shoud be same is second array also
print(after)

[[1 2 3]
 [6 7 8]]
[[1 2 3]
 [6 7 8]]


In [140]:
# veertical stacking vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,6,7,8,9])
np.vstack([v1,v2,v1,v2]) # it will create a 2d matrix stacking the rows on each other as passed in arguments


array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [142]:
np.hstack((v1,v2)) # horizontal stacking

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [ ]:
#Miscellaneous Things

In [ ]:
filedata = np.genfromtxt('data.txt',delimiter = ",") # we can read , seperated values by numpy if want but we can read files usigng pandas also 
filedata = filedata.astype('int32') # this convert the value in to integer 32 bit
print(filedata) 


# here this block will give error because i have no any file data.txt this was for only information 
                       